-- Create the comments table
create table public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  content text not null,
  user_id uuid references auth.users not null,
  post_id uuid -- Optional: Link to a specific post if needed
);

-- Enable Row Level Security
alter table public.comments enable row level security;

-- Policies

-- 1. Select: Everyone can view comments
create policy "Comments are viewable by everyone"
  on public.comments for select
  using ( true );

-- 2. Insert: Authenticated users can insert their own comments
create policy "Users can insert their own comments"
  on public.comments for insert
  to authenticated
  with check ( auth.uid() = user_id );

-- 3. Update: Users can update their own comments
create policy "Users can update their own comments"
  on public.comments for update
  using ( auth.uid() = user_id );

-- 4. Delete: Users can delete their own comments
create policy "Users can delete their own comments"
  on public.comments for delete
  using ( auth.uid() = user_id );
